# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad8988966558550aba80e2cc7e688d355ffc1c12fba6d071b47bd944af39181c8047d1ea179c26ec0a83ba4a9fb2900990a1821674995c88166b4cf7bcafe560

test:
  secret_key_base: 9509b78b5772e545ce4e7e30bbcd4a2c2cde8fd87540d6bd10a12a3acdb5cf5dd9fa539aae58b112f46538b28cc11be756eaeefa2f4712befe7cac0e7903fbc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
